# Generated by Django 5.1.7 on 2025-03-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_subject_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('EEE', 'Electrical & Electronic Engineering'), ('CIVIL', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=10),
        ),
    ]
